# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-22 15:42
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_search', '0008_auto_20180119_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casesearchqueryaddition',
            name='query_addition',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text=b"More information about how this field is used can be found <a href='https://docs.google.com/document/d/1MKllkHZ6JlxhfqZLZKWAnfmlA3oUqCLOc7iKzxFTzdY/edit#heading=h.k5pky76mwwon'>here</a>. This ES <a href='https://www.elastic.co/guide/en/elasticsearch/guide/1.x/bool-query.html'>documentation</a> may also be useful. This JSON will be merged at the `query.filtered.query` path of the query JSON."),
        ),
    ]
