# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-22 21:26
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_search', '0009_auto_20180122_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=256)),
                ('user_id', models.CharField(db_index=True, max_length=256)),
                ('search_criteria', django.contrib.postgres.fields.jsonb.JSONField()),
                ('results', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=256, null=True), size=None)),
                ('converted', models.BooleanField(default=False)),
                ('last_performed', models.DateTimeField(auto_now=True)),
                ('pillow_lag', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
