SMS_INDEX="smslogs_3vouksawmsq9zu97qeeeqnr9vf9eu0r4"
SMS_MAPPING={'_meta': {'comment': 'Modified by Ethan 2014-03-28 for ElasticSearch 1.x syntax',
           'created': None},
 'date_detection': False,
 'date_formats': ['yyyy-MM-dd',
                  "yyyy-MM-dd'T'HH:mm:ssZZ",
                  "yyyy-MM-dd'T'HH:mm:ss.SSSSSS",
                  "yyyy-MM-dd'T'HH:mm:ss.SSSSSS'Z'",
                  "yyyy-MM-dd'T'HH:mm:ss'Z'",
                  "yyyy-MM-dd'T'HH:mm:ssZ",
                  "yyyy-MM-dd'T'HH:mm:ssZZ'Z'",
                  "yyyy-MM-dd'T'HH:mm:ss.SSSZZ",
                  "yyyy-MM-dd'T'HH:mm:ss",
                  "yyyy-MM-dd' 'HH:mm:ss",
                  "yyyy-MM-dd' 'HH:mm:ss.SSSSSS",
                  "mm/dd/yy' 'HH:mm:ss"],
 'dynamic': False,
 'properties': {'backend_api': {'type': 'string'},
                'backend_id': {'type': 'string'},
                'base_doc': {'type': 'string'},
                'billed': {'type': 'boolean'},
                'couch_recipient': {'type': 'string'},
                'couch_recipient_doc_type': {'type': 'string'},
                'date': {'format': "yyyy-MM-dd||yyyy-MM-dd'T'HH:mm:ssZZ||yyyy-MM-dd'T'HH:mm:ss.SSSSSS||yyyy-MM-dd'T'HH:mm:ss.SSSSSS'Z'||yyyy-MM-dd'T'HH:mm:ss'Z'||yyyy-MM-dd'T'HH:mm:ssZ||yyyy-MM-dd'T'HH:mm:ssZZ'Z'||yyyy-MM-dd'T'HH:mm:ss.SSSZZ||yyyy-MM-dd'T'HH:mm:ss||yyyy-MM-dd' 'HH:mm:ss||yyyy-MM-dd' 'HH:mm:ss.SSSSSS||mm/dd/yy' 'HH:mm:ss",
                         'type': 'date'},
                'direction': {'type': 'string'},
                'doc_type': {'index': 'not_analyzed', 'type': 'string'},
                'domain': {'fields': {'exact': {'index': 'not_analyzed'}},
                           'type': 'string'},
                'phone_number': {'type': 'string'},
                'reminder_id': {'type': 'string'},
                'text': {'type': 'string'},
                'workflow': {'type': 'string'},
                'xforms_session_couch_id': {'type': 'string'}}}
