CREATE TABLE IF NOT EXISTS public.household_cases
(
  doc_id text NOT NULL,
  inserted_at text,
  owner_id text NOT NULL,
  awc_id text NOT NULL,
  supervisor_id text,
  block_id text,
  district_id text,
  state_id text,
  open_count integer,
  CONSTRAINT household_cases_pkey PRIMARY KEY (doc_id)
);

CREATE TABLE IF NOT EXISTS public.person_cases
(
  doc_id text NOT NULL,
  inserted_at text,
  owner_id text NOT NULL,
  awc_id text NOT NULL,
  supervisor_id text,
  block_id text,
  district_id text,
  state_id text,
  opened_on date,
  closed_on date,
  sex text,
  dob date,
  age_at_reg integer,
  date_death date,
  resident text,
  name text,
  age_at_death_yrs integer,
  dead_f_resident_neo_count integer,
  dead_m_resident_neo_count integer,
  dead_f_migrant_neo_count integer,
  dead_m_migrant_neo_count integer,
  dead_f_resident_postneo_count integer,
  dead_m_resident_postneo_count integer,
  dead_f_migrant_postneo_count integer,
  dead_m_migrant_postneo_count integer,
  dead_f_resident_child_count integer,
  dead_m_resident_child_count integer,
  dead_f_migrant_child_count integer,
  dead_m_migrant_child_count integer,
  dead_f_migrant_adult_count integer,
  dead_f_resident_adult_count integer,
  dead_pnc_migrant_count integer,
  dead_pnc_resident_count integer,
  dead_del_migrant_count integer,
  dead_del_resident_count integer,
  dead_preg_resident_count integer,
  dead_preg_migrant_count integer,
  dead_preg_count integer,
  female_death_type text,
  pregnant_resident_count integer,
  pregnant_migrant_count integer,
  f_resident_count integer,
  m_resident_count integer,
  f_migrant_count integer,
  m_migrant_count integer,
  referral_health_problem text,
  last_referral_date date,
  referral_reached_date date,
  referral_reached_facility text,
  referred_premature integer,
  referred_sepsis integer,
  referred_diarrhoea integer,
  referred_pneumonia integer,
  referred_fever_child integer,
  referred_severely_underweight integer,
  referred_other_child integer,
  referred_bleeding integer,
  referred_convulsions integer,
  referred_prolonged_labor integer,
  referred_abortion_complications integer,
  referred_fever_discharge integer,
  referred_other integer,
  premature_reached_count integer,
  sepsis_reached_count integer,
  diarrhoea_reached_count integer,
  pneumonia_reached_count integer,
  fever_child_reached_count integer,
  sev_underweight_reached_count integer,
  other_child_reached_count integer,
  bleeding_reached_count integer,
  convulsions_reached_count integer,
  prolonged_labor_reached_count integer,
  abort_comp_reached_count integer,
  fever_discharge_reached_count integer,
  other_reached_count integer,
  open_count integer,
  f_sc_count integer,
  f_st_count integer,
  f_other_count integer,
  m_sc_count integer,
  m_st_count integer,
  m_other_count integer,
  f_minority_count integer,
  f_disabled_count integer,
  m_minority_count integer,
  m_disabled_count integer,
  disability_type_1 integer,
  disability_type_2 integer,
  disability_type_3 integer,
  disability_type_4 integer,
  disability_type_5 integer,
  disability_type_6 integer,
  disabled_movement_count integer,
  disabled_mental_count integer,
  disabled_seeing_count integer,
  disabled_hearing_count integer,
  disabled_speaking_count integer,
  seeking_services integer,
  count integer,
  aadhar_date date,
  CONSTRAINT person_cases_pkey PRIMARY KEY (doc_id)
);