CREATE TABLE IF NOT EXISTS public."config_report_icds-cas_static-awc_location_88b3f9c3"
(
  doc_id text NOT NULL,
  awc_name text,
  awc_site_code text,
  supervisor_id text NOT NULL,
  supervisor_name text NOT NULL,
  supervisor_site_code text NOT NULL,
  block_id text NOT NULL,
  block_name text NOT NULL,
  block_site_code text NOT NULL,
  block_latitude text,
  block_longitude text,
  district_id text NOT NULL,
  district_name text NOT NULL,
  district_site_code text NOT NULL,
  district_latitude text,
  district_longitude text,
  state_id text NOT NULL,
  state_name text NOT NULL,
  state_site_code text NOT NULL,
  state_latitude text,
  state_longitude text,
  CONSTRAINT "config_report_icds-cas_static-awc_location_88b3f9c3_pkey" PRIMARY KEY (doc_id)
);

CREATE TABLE IF NOT EXISTS public."config_report_icds-cas_static-awc_mgt_forms_ad1b11f0"
(
  doc_id text NOT NULL,
  user_id text,
  location_id text,
  block_id text,
  submitted_on date,
  month date,
  count integer,
  awc_location text,
  awc_location_lat numeric(64,16),
  awc_location_long numeric(64,16),
  aww_present integer,
  awc_open integer,
  awc_not_open_aww_not_available integer,
  awc_not_open_closed_early integer,
  awc_not_open_holiday integer,
  awc_not_open_unknown integer,
  awc_not_open_other integer,
  awc_id text,
  CONSTRAINT "config_report_icds-cas_static-awc_mgt_forms_ad1b11f0_pkey" PRIMARY KEY (doc_id)
);

CREATE TABLE IF NOT EXISTS public."config_report_icds-cas_static-ccs_record_cases_cedcca39"
(
  doc_id text NOT NULL,
  inserted_at text,
  owner_id text NOT NULL,
  case_id text NOT NULL,
  awc_id text NOT NULL,
  supervisor_id text,
  block_id text,
  district_id text,
  state_id text,
  opened_on date,
  closed_on date,
  closed integer,
  modified_on date,
  name text,
  edd date,
  add date,
  pregnant_sc_count integer,
  pregnant_st_count integer,
  pregnant_other_count integer,
  pregnant_minority_count integer,
  pregnant_disabled_count integer,
  delivered_sc_count integer,
  delivered_st_count integer,
  delivered_other_count integer,
  delivered_minority_count integer,
  delivered_disabled_count integer,
  person_name text,
  open_count integer,
  open_person_count integer,
  is_pregnant_count integer,
  open_ccs_thr_gte_21 integer,
  ifa_gte_4_open_cases integer,
  complication_type text,
  open_has_complications integer,
  last_date_thr date,
  dob date,
  disabled text,
  caste text,
  minority text,
  resident text,
  date_death date,
  anc1_received integer,
  anc2_received integer,
  anc3_received integer,
  anc4_received integer,
  registration_trimester integer,
  using_ifa_last_visit integer,
  eating_extra_meal_last_visit integer,
  anemia_status_last_visit text,
  bp1_date date,
  bp2_date date,
  bp3_date date,
  tetanus_type text,
  CONSTRAINT "config_report_icds-cas_static-ccs_record_cases_cedcca39_pkey" PRIMARY KEY (doc_id, case_id)
);

CREATE TABLE IF NOT EXISTS public."config_report_icds-cas_static-ccs_record_cases_monthly_33021c88"
(
  doc_id text NOT NULL,
  inserted_at text,
  repeat_iteration integer NOT NULL,
  month date NOT NULL,
  case_id text NOT NULL,
  person_case_id text,
  household_case_id text,
  state_id text,
  district_id text,
  block_id text,
  supervisor_id text,
  awc_id text NOT NULL,
  age_in_months integer,
  age_in_years integer,
  disabled text,
  caste text,
  minority text,
  resident text,
  ccs_status text,
  open_in_month integer,
  alive_in_month integer,
  valid_in_month integer,
  valid_all_registered_in_month integer,
  has_aadhar_id integer,
  trimester integer,
  pregnant integer,
  pregnant_all integer,
  lactating integer,
  lactating_all integer,
  num_rations_distributed integer,
  rations_21_plus_distributed integer,
  thr_eligible integer,
  tetanus_complete integer,
  delivered_in_month integer,
  institutional_delivery_in_month integer,
  anc1_received_at_delivery integer,
  anc2_received_at_delivery integer,
  anc3_received_at_delivery integer,
  anc4_received_at_delivery integer,
  registration_trimester_at_delivery integer,
  using_ifa integer,
  ifa_consumed_last_seven_days integer,
  anemic_severe integer,
  anemic_moderate integer,
  anemic_normal integer,
  anemic_unknown integer,
  extra_meal integer,
  resting_during_pregnancy integer,
  bp_visited_in_month integer,
  pnc_visited_in_month integer,
  trimester_2 integer,
  trimester_3 integer,
  counsel_immediate_bf integer,
  counsel_bp_vid integer,
  counsel_preparation integer,
  counsel_fp_vid integer,
  counsel_immediate_conception integer,
  counsel_accessible_postpartum_fp integer,
  counsel_fp_methods integer,
  form_count text,
  bp1_complete integer,
  bp2_complete integer,
  bp3_complete integer,
  pnc_complete integer,
  postnatal integer,
  CONSTRAINT "config_report_icds-cas_static-ccs_record_cases_monthly_330_pkey" PRIMARY KEY (doc_id, repeat_iteration)
);

CREATE TABLE IF NOT EXISTS public."config_report_icds-cas_static-child_cases_monthly_tabl_d4032f37"
(
  doc_id text NOT NULL,
  inserted_at timestamp without time zone,
  repeat_iteration integer NOT NULL,
  month date NOT NULL,
  case_id text NOT NULL,
  person_case_id text,
  household_case_id text,
  state_id text,
  district_id text,
  block_id text,
  supervisor_id text,
  awc_id text NOT NULL,
  age_in_months integer,
  age_in_years integer,
  sex text,
  disabled text,
  caste text,
  minority text,
  resident text,
  age_tranche integer,
  open_in_month integer,
  alive_in_month integer,
  valid_in_month integer,
  valid_all_registered_in_month integer,
  has_aadhar_id integer,
  wer_eligible integer,
  weight_recorded_in_month numeric(64,16),
  nutrition_status_last_recorded text,
  current_month_nutrition_status text,
  nutrition_status_severely_underweight integer,
  nutrition_status_moderately_underweight integer,
  nutrition_status_normal integer,
  nutrition_status_weighed integer,
  nutrition_status_unweighed integer,
  height_eligible integer,
  height_recorded_in_month numeric(64,16),
  height_measured_in_month integer,
  height_not_measured_in_month integer,
  stunting_last_recorded text,
  current_month_stunting text,
  stunting_severe integer,
  stunting_moderate integer,
  stunting_normal integer,
  wasting_last_recorded text,
  current_month_wasting text,
  wasting_severe integer,
  wasting_moderate integer,
  wasting_normal integer,
  thr_eligible integer,
  num_rations_distributed integer,
  rations_21_plus_distributed integer,
  pse_eligible integer,
  pse_days_attended integer,
  pse_attended_16_days integer,
  born_in_month integer,
  low_birth_weight_born_in_month integer,
  bf_at_birth_born_in_month integer,
  pnc_eligible integer,
  ebf_eligible integer,
  ebf_in_month integer,
  ebf_no_info_recorded integer,
  ebf_not_breastfeeding_reason text,
  ebf_drinking_liquid integer,
  ebf_eating integer,
  ebf_no_bf_no_milk integer,
  ebf_no_bf_pregnant_again integer,
  ebf_no_bf_child_too_old integer,
  ebf_no_bf_mother_sick integer,
  cf_eligible integer,
  cf_in_month integer,
  cf_initiation_eligible integer,
  cf_initiated integer,
  cf_diet_diversity integer,
  cf_diet_quantity integer,
  cf_handwashing integer,
  cf_demo integer,
  fully_immunized_eligible integer,
  fully_immunized_on_time integer,
  fully_immunized_late integer,
  counsel_ebf integer,
  counsel_adequate_bf integer,
  counsel_pediatric_ifa integer,
  counsel_comp_feeding_vid integer,
  counsel_increase_food_bf integer,
  counsel_manage_breast_problems integer,
  counsel_skin_to_skin integer,
  counsel_immediate_breastfeeding integer,
  CONSTRAINT "config_report_icds-cas_static-child_cases_monthly_tabl_d40_pkey" PRIMARY KEY (doc_id, repeat_iteration)
);

CREATE TABLE IF NOT EXISTS public."config_report_icds-cas_static-child_health_cases_a46c129f"
(
  doc_id text NOT NULL,
  inserted_at text,
  person_name text,
  modified_on date,
  opened_on date,
  closed_on date,
  closed integer,
  owner_id text,
  case_id text NOT NULL,
  household_id text NOT NULL,
  mother_id text,
  awc_id text NOT NULL,
  supervisor_id text,
  block_id text,
  district_id text,
  state_id text,
  dob date,
  sex text,
  zscore_grading_wfa text,
  open_count integer,
  birth_weight numeric(64,16),
  weighed_birth_open_count integer,
  lbw_open_count integer,
  last_date_gmp date,
  open_weighed integer,
  is_ebf_open_count integer,
  diet_diversity_open_count integer,
  diet_quantity_open_count integer,
  hand_washing_open_count integer,
  timely_bf_open_count integer,
  comp_feeding_yes_open_count integer,
  is_pretem_or_lbw_open_count integer,
  sev_mal_open_count integer,
  mod_mal_open_count integer,
  norm_mal_open_count integer,
  open_not_weighed_count integer,
  date_death date,
  age_at_death_yrs integer,
  dead_child_count integer,
  resident text,
  disabled text,
  caste text,
  minority text,
  name text,
  mother_name text,
  bf_at_birth text,
  fully_immunized_date date,
  CONSTRAINT "config_report_icds-cas_static-child_health_cases_a46c129f_pkey" PRIMARY KEY (doc_id, case_id)
);

CREATE TABLE IF NOT EXISTS public."config_report_icds-cas_static-daily_feeding_forms_85b1167f"
(
  doc_id text NOT NULL,
  inserted_at text,
  awc_id text,
  supervisor_id text,
  block_id text,
  district_id text,
  state_id text,
  submitted_on date,
  awc_open_count integer,
  open_bfast_count integer,
  open_hotcooked_count integer,
  days_thr_provided_count integer,
  open_pse_count integer,
  open_four_acts_count integer,
  open_one_acts_count integer,
  count integer,
  month date,
  eligible_children integer,
  attended_children integer,
  attended_children_percent numeric,
  attendance_full integer,
  attendance_partial integer,
  attendance_non integer,
  form_location text,
  form_location_lat numeric(64,16),
  form_location_long numeric(64,16),
  awc_not_open_holiday integer,
  awc_not_open_festival integer,
  awc_not_open_no_help integer,
  awc_not_open_department_work integer,
  awc_not_open_other integer,
  awc_not_open integer,
  image_name text,
  CONSTRAINT "config_report_icds-cas_static-daily_feeding_forms_85b1167f_pkey" PRIMARY KEY (doc_id)
);

CREATE TABLE IF NOT EXISTS public."config_report_icds-cas_static-infrastructure_form_05fe0f1a"
(
  doc_id text NOT NULL,
  inserted_at text,
  awc_id text,
  supervisor_id text,
  block_id text,
  district_id text,
  state_id text,
  submitted_on date,
  month date,
  where_housed text,
  provided_building text,
  other_building text,
  awc_building text,
  access_physically_challenged text,
  toilet_facility text,
  type_toilet text,
  source_drinking_water text,
  kitchen text,
  space_storing_supplies text,
  adequate_space_pse text,
  space_pse text,
  medicine_kits_available integer,
  preschool_kit_available integer,
  baby_scale_available integer,
  flat_scale_available integer,
  adult_scale_available integer,
  cooking_utensils_available integer,
  iec_bcc_available integer,
  nhed_kit_available integer,
  referral_slip_available integer,
  plates_available integer,
  tumblers_available integer,
  measure_cups_available integer,
  food_storage_available integer,
  water_storage_available integer,
  chair_available integer,
  table_available integer,
  mats_available integer,
  medicine_kits_usable integer,
  preschool_kit_usable integer,
  baby_scale_usable integer,
  flat_scale_usable integer,
  adult_scale_usable integer,
  cooking_utensils_usable integer,
  iec_bcc_usable integer,
  nhed_kit_usable integer,
  referral_slip_usable integer,
  plates_usable integer,
  tumblers_usable integer,
  measure_cups_usable integer,
  food_storage_usable integer,
  water_storage_usable integer,
  chair_usable integer,
  table_usable integer,
  mats_usable integer,
  use_salt integer,
  type_of_building text,
  type_of_building_pucca integer,
  type_of_building_semi_pucca integer,
  type_of_building_kuccha integer,
  type_of_building_partial_covered_space integer,
  clean_water integer,
  functional_toilet integer,
  has_adequate_space_pse integer,
  CONSTRAINT "config_report_icds-cas_static-infrastructure_form_05fe0f1a_pkey" PRIMARY KEY (doc_id)
);

CREATE TABLE IF NOT EXISTS public."config_report_icds-cas_static-usage_forms_92fbe2aa"
(
  doc_id text NOT NULL,
  inserted_at text,
  awc_id text,
  form_date date,
  month date,
  pse integer,
  gmp integer,
  thr integer,
  add_household integer,
  add_person integer,
  add_pregnancy integer,
  home_visit integer,
  bp_tri1 integer,
  bp_tri2 integer,
  bp_tri3 integer,
  delivery integer,
  pnc integer,
  ebf integer,
  cf integer,
  due_list_ccs integer,
  due_list_child integer,
  pse_time numeric(64,16),
  gmp_time numeric(64,16),
  thr_time numeric(64,16),
  bp_time numeric(64,16),
  delivery_time numeric(64,16),
  pnc_time numeric(64,16),
  ebf_time numeric(64,16),
  cf_time numeric(64,16),
  pse_time_of_day timestamp without time zone,
  home_visit_time_of_day timestamp without time zone,
  CONSTRAINT "config_report_icds-cas_static-usage_forms_92fbe2aa_pkey" PRIMARY KEY (doc_id)
);

CREATE TABLE IF NOT EXISTS public."config_report_icds-cas_static-vhnd_form_28e7fd58"
(
  doc_id text NOT NULL,
  inserted_at text,
  awc_id text,
  supervisor_id text,
  block_id text,
  district_id text,
  state_id text,
  submitted_on date,
  month date,
  vhsnd_date_past_month date,
  done_when_planned integer,
  aww_present integer,
  icds_sup integer,
  asha_present integer,
  anm_mpw integer,
  health_edu_org integer,
  display_tools integer,
  thr_distr integer,
  child_immu integer,
  vit_a_given integer,
  anc_today integer,
  local_leader integer,
  due_list_prep_immunization integer,
  due_list_prep_vit_a integer,
  due_list_prep_antenatal_checkup integer,
  vhnd_gmp integer,
  vhnd_num_pregnant_women integer,
  vhnd_num_lactating_women integer,
  vhnd_num_mothers_6_12 integer,
  vhnd_num_mothers_12 integer,
  vhnd_num_fathers integer,
  CONSTRAINT "config_report_icds-cas_static-vhnd_form_28e7fd58_pkey" PRIMARY KEY (doc_id)
);

CREATE TABLE IF NOT EXISTS public.ucr_table_name_mapping
(
  table_type text NOT NULL,
  table_name text NOT NULL,
  CONSTRAINT table_name_mapping_pkey PRIMARY KEY (table_type, table_name)
);

CREATE TABLE IF NOT EXISTS public.household_cases
(
  doc_id text NOT NULL,
  inserted_at text,
  owner_id text NOT NULL,
  awc_id text NOT NULL,
  supervisor_id text,
  block_id text,
  district_id text,
  state_id text,
  open_count integer,
  CONSTRAINT household_cases_pkey PRIMARY KEY (doc_id)
);

CREATE TABLE IF NOT EXISTS public.person_cases
(
  doc_id text NOT NULL,
  inserted_at text,
  owner_id text NOT NULL,
  awc_id text NOT NULL,
  supervisor_id text,
  block_id text,
  district_id text,
  state_id text,
  opened_on date,
  closed_on date,
  sex text,
  dob date,
  age_at_reg integer,
  date_death date,
  resident text,
  name text,
  age_at_death_yrs integer,
  dead_f_resident_neo_count integer,
  dead_m_resident_neo_count integer,
  dead_f_migrant_neo_count integer,
  dead_m_migrant_neo_count integer,
  dead_f_resident_postneo_count integer,
  dead_m_resident_postneo_count integer,
  dead_f_migrant_postneo_count integer,
  dead_m_migrant_postneo_count integer,
  dead_f_resident_child_count integer,
  dead_m_resident_child_count integer,
  dead_f_migrant_child_count integer,
  dead_m_migrant_child_count integer,
  dead_f_migrant_adult_count integer,
  dead_f_resident_adult_count integer,
  dead_pnc_migrant_count integer,
  dead_pnc_resident_count integer,
  dead_del_migrant_count integer,
  dead_del_resident_count integer,
  dead_preg_resident_count integer,
  dead_preg_migrant_count integer,
  dead_preg_count integer,
  female_death_type text,
  pregnant_resident_count integer,
  pregnant_migrant_count integer,
  f_resident_count integer,
  m_resident_count integer,
  f_migrant_count integer,
  m_migrant_count integer,
  referral_health_problem text,
  last_referral_date date,
  referral_reached_date date,
  referral_reached_facility text,
  referred_premature integer,
  referred_sepsis integer,
  referred_diarrhoea integer,
  referred_pneumonia integer,
  referred_fever_child integer,
  referred_severely_underweight integer,
  referred_other_child integer,
  referred_bleeding integer,
  referred_convulsions integer,
  referred_prolonged_labor integer,
  referred_abortion_complications integer,
  referred_fever_discharge integer,
  referred_other integer,
  premature_reached_count integer,
  sepsis_reached_count integer,
  diarrhoea_reached_count integer,
  pneumonia_reached_count integer,
  fever_child_reached_count integer,
  sev_underweight_reached_count integer,
  other_child_reached_count integer,
  bleeding_reached_count integer,
  convulsions_reached_count integer,
  prolonged_labor_reached_count integer,
  abort_comp_reached_count integer,
  fever_discharge_reached_count integer,
  other_reached_count integer,
  open_count integer,
  f_sc_count integer,
  f_st_count integer,
  f_other_count integer,
  m_sc_count integer,
  m_st_count integer,
  m_other_count integer,
  f_minority_count integer,
  f_disabled_count integer,
  m_minority_count integer,
  m_disabled_count integer,
  disability_type_1 integer,
  disability_type_2 integer,
  disability_type_3 integer,
  disability_type_4 integer,
  disability_type_5 integer,
  disability_type_6 integer,
  disabled_movement_count integer,
  disabled_mental_count integer,
  disabled_seeing_count integer,
  disabled_hearing_count integer,
  disabled_speaking_count integer,
  seeking_services integer,
  count integer,
  aadhar_date date,
  CONSTRAINT person_cases_pkey PRIMARY KEY (doc_id)
);